"""Get Legal Done — AI copilot for legal research and brief writing.

LEGAL DISCLAIMER: This software is a research and drafting assistance tool.
It is NOT a substitute for licensed legal counsel. All output must be reviewed
by a licensed attorney before use in any legal proceeding. No attorney-client
relationship is created by use of this software. Legal research generated by
AI systems may contain errors including hallucinated citations, incorrect
holdings, and outdated law. ALWAYS verify all citations independently.
"""

__version__ = "0.1.0"
